name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies - Download Google Drive files using a script
    - name: Download dependencies from Google Drive
      run: |
        mkdir -p ~/google-drive-downloads/
        # Use a script to download your Maven dependencies from Google Drive
        bash download_from_gdrive.sh 1ODjdNGd0bbJ0ixFNTve6Gb_u6hwS04he ~/google-drive-downloads/across-application-parent-5.1.0.RELEASE.pom
        bash download_from_gdrive.sh 1ODjdNGd0bbJ0ixFNTve6Gb_u6hwS04he ~/google-drive-downloads/across-application-parent-5.1.0.RELEASE.jar

    # Step 3: Install the downloaded dependencies into the local Maven repository (~/.m2/repository)
    - name: Install dependencies locally
      run: |
        mvn install:install-file -Dfile=~/google-drive-downloads/across-application-parent-5.1.0.RELEASE.pom \
          -DgroupId=com.foreach.across \
          -DartifactId=across-application-parent \
          -Dversion=5.1.0.RELEASE \
          -Dpackaging=pom
        mvn install:install-file -Dfile=~/google-drive-downloads/across-application-parent-5.1.0.RELEASE.jar \
          -DgroupId=com.foreach.across \
          -DartifactId=across-application-parent \
          -Dversion=5.1.0.RELEASE \
          -Dpackaging=jar

    # Step 4: Run Maven build with local repository
    - name: Build with Maven
      run: mvn clean install 

    # Step 5: Build and analyze with SonarQube
    - name: Build and analyze
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lamisplus_Consultation-Module_AZHboiDIwnahlNO_STa0
